version: '3.4'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./sources:/var/www/html
      - ./config/php/php:/usr/local/etc/php
    networks:
      - default
      - hasstudio-network

  webserver:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "3100:80"
    volumes:
      - ./sources:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
      - hasstudio-network

networks:
  hasstudio-network:
    external: true
      