version: '3.4'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./sources:/var/www/html
      - ./config/php/php:/usr/local/etc/php
    depends_on:
      - db
    networks:
      hideandseek-network: 

  webserver:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "8181:80"
    depends_on:
      - db
    volumes:
      - ./sources:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      hideandseek-network:

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hideandseek
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin@123
      MYSQL_PASSWORD: admin@123
    ports:
      - "3308:3306"
    networks:
      hideandseek-network:

networks:
  hideandseek-network:
    driver: bridge